  
name: iOS Build

on: [push]

jobs:
  build:
    name: Build phase
    runs-on: macOS-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11']
    steps:
    - uses: actions/checkout@master
    - name: Build and test
      run: |
         xcodebuild clean test -project ActionTest.xcodeproj -scheme ActionTest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env:
         destination: ${{ matrix.destination }}
